### ISSUE TITLE
Improvement modifications from David

### ISSUE THREAD

**Issue by jimhester** [jimhester/primerTree#6]
For each primer pair it would be nice to generate a “summary table” with
- [x]         Average sequence length between primers (with min, max, 5th percentile and 95th percentile)
- [x]     Average pairwise sequence difference in nucleotide (with min, max, 5th percentile and 95th percentile). Ie number of nucleotide differences between any two sequences
-  [x]        Summary of the taxonomy: how many Phylum/Class/Order/Family/Genus/Species are represented in the sequences you get from NCBI (e.g. 1/1/1/1/500/500 would indicate that the primers are amplifying many different genera from the same family)

**Comment by babinecha** [comment]
hello! is it possible now to generate this summary table? how do I get that?
